CREATE TABLE IF NOT EXISTS shops (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    shop_type TEXT,
    shop_sub_type TEXT,
    location TEXT,
    address TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    floor_area_sqft NUMERIC,
    frontage_ft NUMERIC,
    floor_level TEXT,
    suitable_business_types TEXT[],
    target_customers TEXT,
    foot_traffic_level TEXT,
    operating_hours TEXT,
    monthly_rent NUMERIC,
    service_charge NUMERIC DEFAULT 0,
    security_deposit NUMERIC DEFAULT 0,
    customer_parking BOOLEAN DEFAULT false,
    security_24_7 BOOLEAN DEFAULT false,
    power_supply BOOLEAN DEFAULT false,
    water_supply BOOLEAN DEFAULT false,
    loading_bay BOOLEAN DEFAULT false,
    storage_room BOOLEAN DEFAULT false,
    display_windows BOOLEAN DEFAULT false,
    signage_space BOOLEAN DEFAULT false,
    customer_restroom BOOLEAN DEFAULT false,
    air_conditioning BOOLEAN DEFAULT false,
    neighboring_businesses TEXT,
    public_transport_access TEXT,
    market_days TEXT,
    competition_analysis TEXT,
    images TEXT[],
    floor_plan_url TEXT,
    status TEXT DEFAULT 'active',
    featured BOOLEAN DEFAULT false,
    verified BOOLEAN DEFAULT false,
    views INTEGER DEFAULT 0,
    rating NUMERIC DEFAULT 0,
    rating_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);