CREATE TABLE IF NOT EXISTS event_centers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    location TEXT,
    address TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    capacity INTEGER,
    guest_capacity INTEGER,
    indoor_capacity INTEGER,
    outdoor_capacity INTEGER,
    indoor_outdoor TEXT,
    venue_type TEXT,
    venue_sub_type TEXT,
    floor_area_sqft NUMERIC,
    ceiling_height_ft NUMERIC,
    event_types TEXT[],
    catering_kitchen BOOLEAN DEFAULT false,
    catering_allowed BOOLEAN DEFAULT false,
    alcohol_allowed BOOLEAN DEFAULT false,
    decoration_policy TEXT,
    nearby_hotels TEXT,
    minimum_booking INTEGER,
    bar_area BOOLEAN DEFAULT false,
    stage_area BOOLEAN DEFAULT false,
    dance_floor BOOLEAN DEFAULT false,
    av_equipment BOOLEAN DEFAULT false,
    lighting_system BOOLEAN DEFAULT false,
    professional_lighting BOOLEAN DEFAULT false,
    sound_system BOOLEAN DEFAULT false,
    projector_screen BOOLEAN DEFAULT false,
    parking_spaces INTEGER DEFAULT 0,
    valet_parking BOOLEAN DEFAULT false,
    wheelchair_accessible BOOLEAN DEFAULT false,
    bridal_suite BOOLEAN DEFAULT false,
    green_room BOOLEAN DEFAULT false,
    storage_space BOOLEAN DEFAULT false,
    outdoor_space BOOLEAN DEFAULT false,
    garden_area BOOLEAN DEFAULT false,
    pool_area BOOLEAN DEFAULT false,
    restroom_facilities BOOLEAN DEFAULT false,
    wifi_internet BOOLEAN DEFAULT false,
    air_conditioning BOOLEAN DEFAULT false,
    heating_system BOOLEAN DEFAULT false,
    security_system BOOLEAN DEFAULT false,
    security_24_7 BOOLEAN DEFAULT false,
    tables_chairs BOOLEAN DEFAULT false,
    backup_generator BOOLEAN DEFAULT false,
    hourly_rate NUMERIC,
    daily_rate NUMERIC,
    weekend_rate NUMERIC,
    security_deposit NUMERIC DEFAULT 0,
    cleaning_fee NUMERIC DEFAULT 0,
    setup_fee NUMERIC DEFAULT 0,
    overtime_rate NUMERIC DEFAULT 0,
    cancellation_policy TEXT,
    booking_terms TEXT,
    images TEXT[],
    floor_plan_url TEXT,
    virtual_tour_url TEXT,
    status TEXT DEFAULT 'active',
    featured BOOLEAN DEFAULT false,
    verified BOOLEAN DEFAULT false,
    views INTEGER DEFAULT 0,
    rating NUMERIC DEFAULT 0,
    rating_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);