-- Create comprehensive listing tables
CREATE TABLE IF NOT EXISTS sale_properties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  property_type TEXT,
  property_sub_type TEXT,
  location TEXT NOT NULL,
  address TEXT,
  latitude DECIMAL(10,8),
  longitude DECIMAL(11,8),
  bedrooms INTEGER,
  bathrooms INTEGER,
  area_sqm DECIMAL(10,2),
  land_size DECIMAL(10,2),
  sale_price DECIMAL(15,2) NOT NULL,
  price_negotiable BOOLEAN DEFAULT FALSE,
  property_age TEXT,
  property_condition TEXT,
  occupancy_status TEXT,
  reason_for_selling TEXT,
  title_document TEXT,
  nearby_landmarks TEXT,
  images TEXT[],
  video_url TEXT,
  virtual_tour_url TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'pending')),
  featured BOOLEAN DEFAULT FALSE,
  verified BOOLEAN DEFAULT FALSE,
  views INTEGER DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 0,
  rating_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS services (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  service_type TEXT NOT NULL,
  service_category TEXT,
  location TEXT NOT NULL,
  address TEXT,
  service_areas TEXT[],
  pricing TEXT,
  price_min DECIMAL(15,2),
  price_max DECIMAL(15,2),
  experience_years TEXT,
  availability TEXT,
  certifications TEXT,
  licenses TEXT,
  insurance_coverage BOOLEAN DEFAULT FALSE,
  contact_phone TEXT,
  contact_email TEXT,
  business_address TEXT,
  vehicle_types TEXT[],
  coverage_areas TEXT[],
  paint_types TEXT[],
  room_specialization TEXT[],
  assembly_types TEXT[],
  tools_provided BOOLEAN DEFAULT FALSE,
  equipment_list TEXT,
  images TEXT[],
  portfolio_urls TEXT[],
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'pending')),
  featured BOOLEAN DEFAULT FALSE,
  verified BOOLEAN DEFAULT FALSE,
  views INTEGER DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 0,
  rating_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shops (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  shop_type TEXT NOT NULL,
  shop_sub_type TEXT,
  location TEXT NOT NULL,
  address TEXT,
  latitude DECIMAL(10,8),
  longitude DECIMAL(11,8),
  floor_area_sqft DECIMAL(10,2),
  frontage_ft DECIMAL(8,2),
  floor_level TEXT,
  suitable_business_types TEXT[],
  target_customers TEXT,
  foot_traffic_level TEXT,
  operating_hours TEXT,
  monthly_rent DECIMAL(15,2) NOT NULL,
  service_charge DECIMAL(15,2) DEFAULT 0,
  security_deposit DECIMAL(15,2) DEFAULT 0,
  customer_parking BOOLEAN DEFAULT FALSE,
  security_24_7 BOOLEAN DEFAULT FALSE,
  power_supply BOOLEAN DEFAULT FALSE,
  water_supply BOOLEAN DEFAULT FALSE,
  loading_bay BOOLEAN DEFAULT FALSE,
  storage_room BOOLEAN DEFAULT FALSE,
  display_windows BOOLEAN DEFAULT FALSE,
  signage_space BOOLEAN DEFAULT FALSE,
  customer_restroom BOOLEAN DEFAULT FALSE,
  air_conditioning BOOLEAN DEFAULT FALSE,
  neighboring_businesses TEXT,
  public_transport_access TEXT,
  market_days TEXT,
  competition_analysis TEXT,
  images TEXT[],
  floor_plan_url TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'pending')),
  featured BOOLEAN DEFAULT FALSE,
  verified BOOLEAN DEFAULT FALSE,
  views INTEGER DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 0,
  rating_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS event_centers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  venue_type TEXT NOT NULL,
  venue_sub_type TEXT,
  location TEXT NOT NULL,
  address TEXT,
  latitude DECIMAL(10,8),
  longitude DECIMAL(11,8),
  guest_capacity INTEGER,
  indoor_outdoor TEXT,
  area_sqft DECIMAL(10,2),
  hourly_rate DECIMAL(15,2),
  daily_rate DECIMAL(15,2),
  weekend_rate DECIMAL(15,2),
  security_deposit DECIMAL(15,2) DEFAULT 0,
  cleaning_fee DECIMAL(15,2) DEFAULT 0,
  minimum_booking TEXT,
  maximum_booking TEXT,
  setup_time TEXT,
  cleanup_time TEXT,
  catering_allowed BOOLEAN DEFAULT FALSE,
  alcohol_allowed BOOLEAN DEFAULT FALSE,
  music_allowed BOOLEAN DEFAULT TRUE,
  decoration_policy TEXT,
  sound_system BOOLEAN DEFAULT FALSE,
  professional_lighting BOOLEAN DEFAULT FALSE,
  catering_kitchen BOOLEAN DEFAULT FALSE,
  parking_spaces INTEGER DEFAULT 0,
  security_24_7 BOOLEAN DEFAULT FALSE,
  air_conditioning BOOLEAN DEFAULT FALSE,
  stage_platform BOOLEAN DEFAULT FALSE,
  tables_chairs BOOLEAN DEFAULT FALSE,
  restroom_facilities BOOLEAN DEFAULT FALSE,
  wifi_internet BOOLEAN DEFAULT FALSE,
  nearby_hotels TEXT,
  accessibility_features TEXT,
  images TEXT[],
  virtual_tour_url TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'pending')),
  featured BOOLEAN DEFAULT FALSE,
  verified BOOLEAN DEFAULT FALSE,
  views INTEGER DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 0,
  rating_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);