// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvkoywbpymdymhnbubgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2a295d2JweW1keW1obmJ1Ymd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTk0NDAsImV4cCI6MjA3NDM3NTQ0MH0.kQz2hNCke3yMud1WdemO3qSnP0xOv6QqUlZbZteVy4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});